version: "3.4"
services:
  redis:
    restart: always
    image: redis:latest
  mysql_server:
    build:
      context: ./
      target: mysql_server
    restart: always
    volumes:
      - ./data:/var/lib/mysql
  gateway:
    restart: always
    depends_on:
      - redis
      - mysql_server
    build:
      context: ./
      target: cg_gateway
    ports:
      - "8912:8912"
  game:
    restart: always
    depends_on:
      - redis
      - mysql_server
    build:
      context: ./
      target: cg_game
